server:  port: 9999  eureka:  client:    service-url:      defaultZone: http://localhost:1001/eureka  

spring:  application:    name: gateway-service  cloud:    gateway:      discovery:        locator:          enabled: false
          lower-case-service-id: true      routes:      - id: cloud-service-b        uri: lb://cloud-service-b        predicates:          - Path=/sb/**        filters:          - StripPrefix=1  
      - id: cloud-service-a        uri: lb://cloud-service-a        predicates:          - Path=/sa/**        filters:          - StripPrefix=1




